default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: whiteBox_development

test:
  <<: *default
  database: whiteBox_test

production:
  <<: *default
  database: whiteBox_production
  username: whiteBox
  password: <%= ENV['WHITEBOX_DATABASE_PASSWORD'] %>
